# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.8 on 2017-02-01 20:28
=======
# Generated by Django 1.9.8 on 2016-10-13 12:54
>>>>>>> ac50553faec791c444feec1d8a25df18f1b09951
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('roll', models.CharField(max_length=10)),
                ('contactNo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
=======
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=80)),
                ('github_name', models.CharField(max_length=80)),
                ('alias', models.CharField(default=1, max_length=80)),
>>>>>>> ac50553faec791c444feec1d8a25df18f1b09951
            ],
        ),
    ]
