# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('roll', models.CharField(max_length=10)),
                ('contactNo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
            ],
        ),
    ]
