# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Behance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.CharField(default=' ', max_length=32),
        ),
        migrations.AddField(
            model_name='member',
            name='codechef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='contactNo',
            field=models.CharField(max_length=10),
        ),
    ]
