# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170406_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='MemberProfile',
        ),
    ]
