# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labstatus',
            options={'verbose_name_plural': 'Lab Status'},
        ),
    ]
