# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20171102_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='user',
        ),
    ]
